name: Build website

on:
  workflow_dispatch:
  push:
    branches: [ main ]

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Generate
      uses: CultureHQ/actions-yarn@v1.0.1
    - run: yarn --frozen-lockfile
    - run: yarn run docs:build
    - name: Create CNAME file
      uses: finnp/create-file-action@master
      env:
        FILE_NAME: "docs/.vitepress/dist/CNAME"
        FILE_DATA: "next.ukonline.be"
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: docs/.vitepress/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
